apiVersion: ostia.3scale.net/v1alpha1
kind: API
metadata:
  name: hello
spec:
  expose: true
  hostname: hello.127.0.0.1.nip.io
  endpoints:
    - name: hello
      host: https://echo-api.3scale.net
      path: /hello